### PR TITLE
updates for eft

### PR DESCRIPTION
**Pull request by levensailor**
Added

ADMIN
- Resource Groups
- Resource Group Memberships

USER
- Attachment Actions
- Devices
- Place Services
- Places
- xAPI

### CODE REVIEW

**Comment by levensailor** [comment]
You can wait until this is GA to merge. I'll monitor and if anything changes during the EFT, I'll cancel and resubmit with changes

**Comment by ObjectIsAdvantag** [comment]
thanks Jeff

**Comment by ObjectIsAdvantag** [comment]
hi Jeff, I am thinking to integrate the updates into distinct collections, depending on the purposes: user / admin but also bots or devices. Not sure if having all features in a single collection is that usefull, I have spread my Webex collections, currently I have:
- Teams API V1 (user)
- Admin API (admin) with /devices & /places
- Cards (bot and user)
- Devices (on-prem xAPI)
- Devices Admin (on-prem xAPI)
- Devices Cloud (/xapi) where I've put everything needed to activate a device too so /devices & /places (redundant)

thoughts @levensailor

**Comment by ObjectIsAdvantag** [comment]
So I just updated these existing postman collections:
- Teams API V1 (user) with /attachment/actions
- Admin API (admin) with /devices & /places
- Cards (bot and user) with /attachment/actions

@levensailor Jeef, I looked at your proposal for /ResourceGroups & Memberships , these would need scripts added

**Comment by ObjectIsAdvantag** [comment]
Also /places/services won't make it out of EFT.

So would suggest to pull the latest collection for admins and add /ResourceGroups & Memberships with scripts.
Creating issue #4  for that purpose if you feel like contributing , please do!

**Pull request closed without merging**
